spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gradu
    username: juhwan
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always

logging.level:
  org.hibernate.SQL: debug