spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gradu
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  messages:
    basename: messages, errors
  profiles:
    include: secret

logging.level:
  org.hibernate.SQL: info