spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gradu
    username: juhwan
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always

logging.level:
  org.hibernate.SQL: debug

sns.google:
  url: https://accounts.google.com/o/oauth2/v2/auth
  client:
    id: 700692001238-mfd7ltevs0i9m5t1qf1i5dmurj850jtm.apps.googleusercontent.com
    secret: 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
  callback:
    url: http://localhost:8080/auth/google/callback
  token:
    url: https://oauth2.googleapis.com/token
  user:
    url: https://www.googleapis.com/oauth2/v1/userinfo

api.naver:
  url: https://nid.naver.com/oauth2.0/authorize
  client:
    id: MVC4nhG5uQd9ZjCb2gaq
    secret: Ewaf59sA0F
  callback:
    url: http://localhost:8080/auth/naver/callback
  token:
    url: https://nid.naver.com/oauth2.0/token
  user:
    url: https://openapi.naver.com/v1/nid/me
